import torch
import joblib
import pandas as pd
from surprise import SVD, Dataset, Reader
from src.dataset import TextPreprocessor
from src.sentiment_engine import SentimentAnalyzer, BrandHealthEngine
from src.recommender import prepare_recommendation_data

def run_training():
    DATA_PATH = "GrammarandProductReviews.csv"
    DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

    # Step 1: Preprocessing
    print("Step 1: Cleaning Data...")
    preprocessor = TextPreprocessor()
    df = preprocessor.process_dataframe(DATA_PATH)

    # Step 2: Sentiment & Brand Metrics
    print("Step 2: Calculating Brand Health and Trends...")
    analyzer = SentimentAnalyzer(device=DEVICE)
    df = analyzer.run_batch_sentiment(df)
    
    health_engine = BrandHealthEngine()
    brand_health = health_engine.calculate_brand_health(df)
    brand_trends = health_engine.predict_trends(df)

    # Step 3: Train SVD Model
    print("Step 3: Training Recommendation Model...")
    df = prepare_recommendation_data(df)
    reader = Reader(rating_scale=(1, 5))
    # 'id' is generated by prepare_recommendation_data
    data_svd = Dataset.load_from_df(df[['reviews.username', 'id', 'reviews.rating']], reader)
    trainset = data_svd.build_full_trainset()
    
    svd_model = SVD()
    svd_model.fit(trainset)

    # Step 4: Save Artifacts for main.py
    df.to_csv("processed_data.csv", index=False)
    brand_health.to_csv("brand_health_lookup.csv", index=False)
    brand_trends.to_csv("brand_trend_monthly.csv", index=False)
    joblib.dump(svd_model, "svd_model.pkl")
    print("Success: All models and data saved!")

if __name__ == "__main__":
    run_training()